apiVersion: v1

kind: Namespace

metadata:

  name: kep-library

---

apiVersion: v1

kind: Service

metadata:

  name: kep-library

spec:

  type: LoadBalancer

  ports:

  - port: 80

    targetPort: 8080

  selector:

    app: kep-library 
